/**
 * Function schema types for RayfinClient.
 *
 * Normally AUTO-GENERATED by `rayfin dev functions apply` -- hand-written
 * here instead because that command needs Azure Functions Core Tools
 * locally (not installed in this environment) and, separately, Fabric
 * doesn't support deploying Functions to production yet as of 2026-09-17
 * ("Functions are not supported yet" 400 from `rayfin up`). This type is
 * copied by hand from getFingerprint's real signature in
 * rayfin/functions/src/function_app.ts -- keep the two in sync manually
 * until either blocker clears and real typegen takes over again.
 *
 * The schema is a closed object type: only the function names listed
 * below are accepted by RayfinClient.functions.<name>.invoke(...).
 *
 * IMPORTANT: This file must NOT import any Node.js packages — it is
 * resolved by the frontend app's TypeScript compiler.
 */

export type AppFunctionsSchema = {
  getFingerprint: {
    input: {
      stationEoi: string;
      pollutant: 'NO2' | 'PM10' | 'PM2.5';
      /** ISO date, inclusive. */
      periodStart: string;
      /** ISO date, exclusive. */
      periodEnd: string;
      /** Omit to use an approximate 90th-percentile default. */
      threshold?: number;
    };
    output: {
      grid: Array<{
        sectorIndex: number;
        binSortOrder: number;
        binLabel: string;
        meanConcentration: number;
        n: number;
      }>;
      cpf: Array<{
        sectorIndex: number;
        cpf: number;
        n: number;
        exceedances: number;
      }>;
      threshold: number;
      validHours: number;
    };
  };
};
