// Validates seed/campaign.json + seed/scenarios.json and, on a real run,
// generates seed/seed.sql from them.
//
// This repo ships no backend, so there is no database to write to directly.
// The seedable artifact is idempotent T-SQL: create-if-absent DDL, ALTER
// guards that add the campaign columns with a DEFAULT of 1 so a database
// already holding pre-campaign rows survives the schema change, then MERGE
// upserts on the business keys. Run it against whatever SQL database the
// app is eventually pointed at.
//
// Usage:
//   npm run seed -- --dry-run    validate and print the plan, write nothing
//   npm run seed                 validate, then write seed/seed.sql
//
// Validation lives in src/game/validate.ts, is pure, and is unit-tested.
// This file is only the I/O shell around it.

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  scenarioWeek,
  validateContent,
  type AuthoredScenario,
  type AuthoredWeek,
} from '../src/game/validate.ts';

const projectRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const seedDir = join(projectRoot, 'seed');

function readJson(fileName: string): unknown {
  return JSON.parse(readFileSync(join(seedDir, fileName), 'utf-8'));
}

function loadScenarios(): AuthoredScenario[] {
  const raw = readJson('scenarios.json') as { scenarios?: AuthoredScenario[] };
  if (!Array.isArray(raw.scenarios)) {
    throw new Error('seed/scenarios.json has no "scenarios" array.');
  }
  return raw.scenarios;
}

function loadWeeks(): AuthoredWeek[] {
  const raw = readJson('campaign.json') as { weeks?: AuthoredWeek[] };
  if (!Array.isArray(raw.weeks)) {
    throw new Error('seed/campaign.json has no "weeks" array.');
  }
  return raw.weeks;
}

/** N'...' literal with quotes doubled. */
function q(value: string): string {
  return `N'${value.replace(/'/g, "''")}'`;
}

function qOpt(value: string | undefined): string {
  return value === undefined ? 'NULL' : q(value);
}

function bit(value: boolean): string {
  return value ? '1' : '0';
}

function buildSql(scenarios: AuthoredScenario[], weeks: AuthoredWeek[]): string {
  const scenarioRows = scenarios
    .map(
      (s) =>
        `    (${q(s.id)}, ${scenarioWeek(s)}, ${s.day}, ${q(s.domain)}, ` +
        `${q(s.objective)}, ${q(s.title)}, ${q(s.incident)}, ` +
        `${bit(s.isFollowUp ?? false)})`
    )
    .join(',\n');

  const optionRows = scenarios
    .flatMap((s) =>
      s.options.map(
        (o) =>
          `    (${q(s.id)}, ${q(o.id)}, ${q(o.text)}, ${o.cuCost}, ` +
          `${o.slaDelta}, ${bit(o.correct)}, ${q(o.feedback)}, ${qOpt(o.followUp)})`
      )
    )
    .join(',\n');

  const weekList = weeks
    .map(
      (w) =>
        `--   week ${w.number} "${w.title}": ${w.days} days, ` +
        `${w.startingCu} CU / ${w.startingSla} SLA`
    )
    .join('\n');

  return `-- Generated by scripts/seed.ts from seed/scenarios.json and
-- seed/campaign.json. Idempotent: safe to rerun. Do not edit by hand; edit
-- the JSON and regenerate with: npm run seed
--
-- Campaign configured in seed/campaign.json:
${weekList}
--
-- Week structure itself is NOT stored in the database. Rows only record
-- which week they belong to; day counts and budgets stay in campaign.json.

SET XACT_ABORT ON;
BEGIN TRANSACTION;

-- Reference data ------------------------------------------------------------

IF OBJECT_ID('dbo.Scenarios', 'U') IS NULL
CREATE TABLE dbo.Scenarios (
    id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
    code NVARCHAR(10) NOT NULL UNIQUE,
    week INT NOT NULL DEFAULT 1,
    [day] INT NOT NULL,
    domain NVARCHAR(30) NOT NULL,
    objective NVARCHAR(100) NOT NULL,
    title NVARCHAR(100) NOT NULL,
    incident NVARCHAR(1000) NOT NULL,
    isFollowUp BIT NOT NULL DEFAULT 0
);

IF OBJECT_ID('dbo.ScenarioOptions', 'U') IS NULL
CREATE TABLE dbo.ScenarioOptions (
    id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
    scenario_id UNIQUEIDENTIFIER NOT NULL
        REFERENCES dbo.Scenarios (id) ON DELETE CASCADE,
    optionKey NVARCHAR(5) NOT NULL,
    optionText NVARCHAR(500) NOT NULL,
    cuCost INT NOT NULL,
    slaDelta INT NOT NULL,
    correct BIT NOT NULL DEFAULT 0,
    feedback NVARCHAR(1000) NOT NULL,
    followUpCode NVARCHAR(10) NULL,
    CONSTRAINT UQ_ScenarioOptions_key UNIQUE (scenario_id, optionKey)
);

-- Telemetry -----------------------------------------------------------------

IF OBJECT_ID('dbo.Sessions', 'U') IS NULL
CREATE TABLE dbo.Sessions (
    id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
    userId NVARCHAR(100) NOT NULL,
    startedAt DATETIME2 NOT NULL,
    completedAt DATETIME2 NULL,
    weekNumber INT NOT NULL DEFAULT 1,
    cuRemaining INT NOT NULL DEFAULT 100,
    slaScore INT NOT NULL DEFAULT 100,
    currentDay INT NOT NULL DEFAULT 1,
    completed BIT NOT NULL DEFAULT 0,
    -- "completed" or "breached". A run that ran out of capacity still sets
    -- completed, because the session did finish; this says whether the week
    -- was survived.
    outcome NVARCHAR(20) NOT NULL DEFAULT 'completed'
);

-- Append-only, and denormalized on purpose: the analytics notebook reads
-- this table on its own, with no joins, so mastery can be plotted as a
-- learning curve across the campaign instead of a single average.
IF OBJECT_ID('dbo.AttemptEvents', 'U') IS NULL
CREATE TABLE dbo.AttemptEvents (
    id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
    session_id UNIQUEIDENTIFIER NOT NULL
        REFERENCES dbo.Sessions (id),
    userId NVARCHAR(100) NOT NULL,
    scenarioCode NVARCHAR(10) NOT NULL,
    weekNumber INT NOT NULL DEFAULT 1,
    domain NVARCHAR(30) NOT NULL,
    objective NVARCHAR(100) NOT NULL,
    chosenOptionKey NVARCHAR(5) NOT NULL,
    correct BIT NOT NULL,
    cuCost INT NOT NULL,
    slaDelta INT NOT NULL,
    secondsToDecide INT NOT NULL,
    createdAt DATETIME2 NOT NULL
);

-- Campaign columns on databases that predate the campaign. NOT NULL with a
-- DEFAULT of 1, so rows already deployed become week 1 rather than null.

IF COL_LENGTH('dbo.Scenarios', 'week') IS NULL
ALTER TABLE dbo.Scenarios
    ADD week INT NOT NULL CONSTRAINT DF_Scenarios_week DEFAULT 1 WITH VALUES;

IF COL_LENGTH('dbo.Sessions', 'weekNumber') IS NULL
ALTER TABLE dbo.Sessions
    ADD weekNumber INT NOT NULL CONSTRAINT DF_Sessions_weekNumber DEFAULT 1 WITH VALUES;

IF COL_LENGTH('dbo.AttemptEvents', 'weekNumber') IS NULL
ALTER TABLE dbo.AttemptEvents
    ADD weekNumber INT NOT NULL CONSTRAINT DF_AttemptEvents_weekNumber DEFAULT 1 WITH VALUES;

-- Rows written before a week could be lost were all survivable, so they
-- default to "completed" rather than being backfilled.
IF COL_LENGTH('dbo.Sessions', 'outcome') IS NULL
ALTER TABLE dbo.Sessions
    ADD outcome NVARCHAR(20) NOT NULL CONSTRAINT DF_Sessions_outcome DEFAULT 'completed' WITH VALUES;

-- Content upsert ------------------------------------------------------------

MERGE dbo.Scenarios AS t
USING (VALUES
${scenarioRows}
) AS s (code, week, [day], domain, objective, title, incident, isFollowUp)
ON t.code = s.code
WHEN MATCHED THEN UPDATE SET
    week = s.week,
    [day] = s.[day],
    domain = s.domain,
    objective = s.objective,
    title = s.title,
    incident = s.incident,
    isFollowUp = s.isFollowUp
WHEN NOT MATCHED THEN INSERT (code, week, [day], domain, objective, title, incident, isFollowUp)
    VALUES (s.code, s.week, s.[day], s.domain, s.objective, s.title, s.incident, s.isFollowUp);

MERGE dbo.ScenarioOptions AS t
USING (
    SELECT sc.id AS scenario_id, v.optionKey, v.optionText, v.cuCost,
           v.slaDelta, v.correct, v.feedback, v.followUpCode
    FROM (VALUES
${optionRows}
    ) AS v (scenarioCode, optionKey, optionText, cuCost, slaDelta, correct, feedback, followUpCode)
    INNER JOIN dbo.Scenarios sc ON sc.code = v.scenarioCode
) AS s
ON t.scenario_id = s.scenario_id AND t.optionKey = s.optionKey
WHEN MATCHED THEN UPDATE SET
    optionText = s.optionText,
    cuCost = s.cuCost,
    slaDelta = s.slaDelta,
    correct = s.correct,
    feedback = s.feedback,
    followUpCode = s.followUpCode
WHEN NOT MATCHED THEN INSERT (scenario_id, optionKey, optionText, cuCost, slaDelta, correct, feedback, followUpCode)
    VALUES (s.scenario_id, s.optionKey, s.optionText, s.cuCost, s.slaDelta, s.correct, s.feedback, s.followUpCode)
WHEN NOT MATCHED BY SOURCE THEN DELETE;

COMMIT TRANSACTION;

SELECT week, COUNT(*) AS scenarios
FROM dbo.Scenarios
GROUP BY week
ORDER BY week;
`;
}

function main(): void {
  const dryRun = process.argv.includes('--dry-run');
  const scenarios = loadScenarios();
  const weeks = loadWeeks();

  const errors = validateContent(scenarios, weeks);
  if (errors.length > 0) {
    console.error('Seed content failed validation:');
    for (const e of errors) console.error(`  - ${e}`);
    process.exit(1);
  }

  const optionCount = scenarios.reduce((n, s) => n + s.options.length, 0);
  console.log(
    `Validated ${weeks.length} weeks, ${scenarios.length} scenarios, ${optionCount} options.`
  );

  for (const w of weeks) {
    const inWeek = scenarios.filter((s) => scenarioWeek(s) === w.number);
    const playable = inWeek.filter((s) => !s.isFollowUp).length;
    console.log(
      `Week ${w.number} "${w.title}": ${w.days} days, ${playable} incidents, ` +
        `${inWeek.length - playable} follow-ups, ${w.startingCu} CU / ${w.startingSla} SLA`
    );
    if (dryRun) {
      for (const s of inWeek) {
        const tag = s.isFollowUp ? ' [follow-up]' : '';
        console.log(
          `  upsert ${s.id} (day ${s.day}, ${s.domain})${tag}: ${s.options.length} options`
        );
      }
    }
  }

  if (dryRun) {
    console.log('Dry run only; nothing was written.');
    return;
  }

  const outPath = join(seedDir, 'seed.sql');
  writeFileSync(outPath, buildSql(scenarios, weeks), 'utf-8');
  console.log(`Wrote ${outPath}.`);
}

main();
