// Generates seed/seed.sql from seed/scenarios.json: idempotent T-SQL that
// upserts Scenarios and ScenarioOptions (MERGE on the business keys) and
// deletes options removed from the JSON.
//
// This is the deployed-backend fallback for scripts/seed.ts: the Fabric
// backend rejects email/password auth entirely ("Password authentication is
// not enabled for this project"), so the typed-client seed path cannot sign
// in. Run the generated SQL against the workspace SQL database instead,
// either in the Fabric portal query editor or with any Entra-authenticated
// SQL client.
//
// Usage: npx tsx scripts/seed-sql.ts   (writes seed/seed.sql)

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

interface SeedOption {
  id: string;
  text: string;
  cuCost: number;
  slaDelta: number;
  correct: boolean;
  feedback: string;
  followUp?: string;
}

interface SeedScenario {
  id: string;
  week: number;
  day: number;
  domain: string;
  objective: string;
  title: string;
  incident: string;
  isFollowUp?: boolean;
  options: SeedOption[];
}

const projectRoot = join(dirname(fileURLToPath(import.meta.url)), '..');

function q(value: string): string {
  return `N'${value.replace(/'/g, "''")}'`;
}

function qOpt(value: string | undefined): string {
  return value === undefined ? 'NULL' : q(value);
}

function bit(value: boolean): string {
  return value ? '1' : '0';
}

const raw = JSON.parse(
  readFileSync(join(projectRoot, 'seed', 'scenarios.json'), 'utf-8')
);
const scenarios = raw.scenarios as SeedScenario[];

const scenarioRows = scenarios
  .map(
    (s) =>
      `    (${q(s.id)}, ${s.week}, ${s.day}, ${q(s.domain)}, ${q(s.objective)}, ` +
      `${q(s.title)}, ${q(s.incident)}, ${bit(s.isFollowUp ?? false)})`
  )
  .join(',\n');

const optionRows = scenarios
  .flatMap((s) =>
    s.options.map(
      (o) =>
        `    (${q(s.id)}, ${q(o.id)}, ${q(o.text)}, ${o.cuCost}, ` +
        `${o.slaDelta}, ${bit(o.correct)}, ${q(o.feedback)}, ${qOpt(o.followUp)})`
    )
  )
  .join(',\n');

const sql = `-- Generated by scripts/seed-sql.ts from seed/scenarios.json.
-- Idempotent: safe to rerun. Do not edit by hand; edit scenarios.json and
-- regenerate with: npx tsx scripts/seed-sql.ts

SET XACT_ABORT ON;
BEGIN TRANSACTION;

MERGE dbo.Scenarios AS t
USING (VALUES
${scenarioRows}
) AS s (code, week, [day], domain, objective, title, incident, isFollowUp)
ON t.code = s.code
WHEN MATCHED THEN UPDATE SET
    week = s.week,
    [day] = s.[day],
    domain = s.domain,
    objective = s.objective,
    title = s.title,
    incident = s.incident,
    isFollowUp = s.isFollowUp
WHEN NOT MATCHED THEN INSERT (id, code, week, [day], domain, objective, title, incident, isFollowUp)
    VALUES (NEWID(), s.code, s.week, s.[day], s.domain, s.objective, s.title, s.incident, s.isFollowUp);

MERGE dbo.ScenarioOptions AS t
USING (
    SELECT sc.id AS scenario_id, v.optionKey, v.optionText, v.cuCost,
           v.slaDelta, v.correct, v.feedback, v.followUpCode
    FROM (VALUES
${optionRows}
    ) AS v (scenarioCode, optionKey, optionText, cuCost, slaDelta, correct, feedback, followUpCode)
    INNER JOIN dbo.Scenarios sc ON sc.code = v.scenarioCode
) AS s
ON t.scenario_id = s.scenario_id AND t.optionKey = s.optionKey
WHEN MATCHED THEN UPDATE SET
    optionText = s.optionText,
    cuCost = s.cuCost,
    slaDelta = s.slaDelta,
    correct = s.correct,
    feedback = s.feedback,
    followUpCode = s.followUpCode
WHEN NOT MATCHED THEN INSERT (id, scenario_id, optionKey, optionText, cuCost, slaDelta, correct, feedback, followUpCode)
    VALUES (NEWID(), s.scenario_id, s.optionKey, s.optionText, s.cuCost, s.slaDelta, s.correct, s.feedback, s.followUpCode)
WHEN NOT MATCHED BY SOURCE THEN DELETE;

COMMIT TRANSACTION;

SELECT (SELECT COUNT(*) FROM dbo.Scenarios) AS scenarios,
       (SELECT COUNT(*) FROM dbo.ScenarioOptions) AS options;
`;

const outPath = join(projectRoot, 'seed', 'seed.sql');
writeFileSync(outPath, sql, 'utf-8');
const weeks = [...new Set(scenarios.map((s) => s.week))].sort((a, b) => a - b);
console.log(
  `Wrote ${outPath}: ${scenarios.length} scenarios across weeks ${weeks.join(', ')}, ` +
    `${scenarios.reduce((n, s) => n + s.options.length, 0)} options.`
);
